Project/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('core.urls'))
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

core/urls.py
from django.urls import path
from core import views
from django.views.generic import TemplateView

app_name = "core"

urlpatterns = [
	path('',views.home,name = 'home'),
	path('menu/',views.menu,name = 'menu'),
	path('checkout/',views.checkout,name = 'checkout'),
	path('track-order/',views.track_order,name = 'track_order'),
	path('api/track-order/<slug:number>/',views.track_order_num,name = 'track_order_num'),

	path('thank-you/<slug:number>/', views.thank_you,name="thank_you"),
	path('product/<int:pk>/', views.product,name="product"),

	path('cart/', TemplateView.as_view(template_name="cart.html"),name="cart"),
    path('about/', TemplateView.as_view(template_name="about.html"),name="about"),
    path('contact/', TemplateView.as_view(template_name="contact.html"),name="contact"),
]

core/models.py
from django.db import models

class Product(models.Model):
	catagory = models.CharField(max_length=100)
	name = models.CharField(max_length=100)
	description = models.CharField(max_length=250)
	image = models.CharField(max_length=100)
	sm_image = models.CharField(max_length=100)
	has_offer = models.BooleanField(default=False)
	price = models.FloatField(default=12.99)

	def __str__(self):
		return self.name

class Size(models.Model):
	name = models.CharField(max_length=10)
	price = models.FloatField()
	product = models.ManyToManyField(Product)

	def __str__(self):
		return self.name 


class Order(models.Model):
	name = models.CharField(max_length=100)
	email = models.CharField(max_length=100)
	phone = models.CharField(max_length=100)
	country = models.CharField(max_length=100)
	city = models.CharField(max_length=100)
	address_1 = models.CharField(max_length=100)
	address_2 = models.CharField(max_length=100, blank=True, null=True)
	order_id = models.CharField(max_length=100, blank=True, null=True)
	state = models.CharField(max_length=100, default='Processing')
	total = models.FloatField(blank=True, null=True)
	tax = models.FloatField(default=0, blank=True, null=True)

	def __str__(self):
		return self.name

class OrderItem(models.Model):
	name = models.CharField(max_length=100)
	price = models.FloatField()
	quantity = models.IntegerField()
	size_name = models.CharField(max_length=10)
	order = models.ForeignKey(Order, on_delete=models.CASCADE)

	def __str__(self):
		return self.name

core/forms.py
from django.forms import ModelForm

from core.models import Order 


class OrderForm(ModelForm):
	class Meta:
		model = Order
		exclude = ['order_id','state','total','total']

core/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.http import JsonResponse

from core.forms import OrderForm
from core.models import Product,Size,Order,OrderItem

import random
import json


def home(request):
	return render(request, "home.html")

def menu(request):
	return render(request,"menu.html", {'products': Product.objects.all()})

def checkout(request):
	if request.method == "POST":
		f = OrderForm(request.POST)
		if f.is_valid():
			o = f.save()
			total = 0
			for i in json.loads(request.POST.get("data"))['data']:
				p = Product.objects.filter(pk = int(i['p']))[0]
				s = Size.objects.filter(pk = int(i['s']))[0]
				OrderItem.objects.create(order = o,name = p.name,price = s.price,size_name = s.name,quantity = int(i['q']))
				total += s.price*int(i['q'])
			o.order_id = ''.join(random.choices("0123456789",k = 6))
			o.total = total
			o.save()
			return redirect("core:thank_you",number = o.order_id)
	return render(request,"checkout.html")

def product(request, pk):
	product = get_object_or_404(Product, pk=pk)
	pizzas = Product.objects.filter(catagory='Pizzas')[:3]
	sizes = Size.objects.filter(product=product)
	return render(request,"product.html",{'product': product,'pizzas': pizzas,'sizes': sizes})

def thank_you(request, number):
	return render(request, "thankyou.html", {'number': number})

def track_order(request):
	return render(request, "track_order.html")

def track_order_num(request, number):
	order = Order.objects.filter(order_id=number)
	if order:
		return JsonResponse({"message":f"Hello {order[0].name}! Your Order Status is : {order[0].state}"})
	return JsonResponse({"message":f"Order Not Found!"})

core/templates/cart.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
  <title>Cart Page</title>
{% endblock %}

{% block content %}

  <!-- Subheader Start -->
  <div class="subheader dark-overlay dark-overlay-2" style="background-image: url({% static 'img/subheader.jpg' %})">
    <div class="container">
      <div class="subheader-inner">
        <h1>Cart</h1>
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'core:home' %}">Home</a></li>
            <li class="breadcrumb-item active" aria-current="page">Cart</li>
          </ol>
        </nav>
      </div>

    </div>
  </div>
  <!-- Subheader End -->

  <!--Cart Start -->
  <section class="section">
    <div class="container page-cartt">

      <!-- Cart Table Start -->
      <table class="ct-responsive-table">
        <thead>
          <tr>
            <th class="remove-item"></th>
            <th>Product</th>
            <th>Price</th>
            <th>Qunantity</th>
            <th>Total</th>
          </tr>
        </thead>
        <tbody class="cart-table">

          <tr>
            <td class="remove">
              <button type="button" class="close-btn close-danger remove-from-cart">
                <span></span>
                <span></span>
              </button>
            </td>
            <td data-title="Product">
              <div class="cart-product-wrapper">
                <img src="{% static 'img/3.png' %}" alt="prod1">
                <div class="cart-product-body">
                  <h6> <a href="#">Four Cheese</a> </h6>
                  <p>21 Inch</p>
                  <p>Extra Cheese</p>
                </div>
              </div>
            </td>
            <td data-title="Price"> <strong>13.99$</strong> </td>
            <td class="quantity" data-title="Quantity">
              <input type="number" class="qty form-control" value="1">
            </td>
            <td data-title="Total"> <strong>13.99$</strong> </td>
          </tr>

        </tbody>
      </table>
      <!-- Cart Table End -->

      <!-- Cart form Start -->
      <div class="row ct-cart-form">
        <div class="offset-lg-6 col-lg-6">
          <h4>Cart Total</h4>
          <table>
            <tbody>
              <tr>
                <th>Subtotal</th>
                <td class="saba">90.99$</td>
              </tr>
              <tr>
                <th>Tax</th>
                <td> 0$</td>
              </tr>
              <tr>
                <th>Total</th>
                <td> <b class="daba">99.99$</b> </td>
              </tr>
            </tbody>
          </table>
          <a href="{% url 'core:checkout' %}" class="btn-custom primary btn-block">Proceeed to Checkout</a>
        </div>
      </div>
      <!-- Cart form End -->

    </div>
  </section>
  <!-- Cart End -->

{% endblock %}


{% block javascript %}

<script type="text/javascript">


</script>

{% endblock %}

core/templates/checkout.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
  <title>Checkout</title>
{% endblock %}

{% block content %}

  <!-- Subheader Start -->
  <div class="subheader dark-overlay dark-overlay-2" style="background-image: url({% static 'img/subheader.jpg' %})">
    <div class="container">
      <div class="subheader-inner">
        <h1>Checkout</h1>
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'core:home' %}">Home</a></li>
            <li class="breadcrumb-item active" aria-current="page">Checkout</li>
          </ol>
        </nav>
      </div>

    </div>
  </div>
  <!-- Subheader End -->

  <!-- Checkout Start -->
  <section class="section">
    <div class="container page-checkoutcartt">

      <form method="post" class="checkout-form">
        {% csrf_token %}
        <div class="row">
          <div class="col-xl-7">

            <!-- Buyer Info -->
            <h4>Billing Details</h4>
            <div class="row">
              <div class="form-group col-xl-6">
                <label>Full Name <span class="text-danger">*</span></label>
                <input type="text" placeholder="Full Name" name="name" class="form-control" required="">
              </div>
              <div class="form-group col-xl-6">
                <label>Email Address <span class="text-danger">*</span></label>
                <input type="email" placeholder="Email Address" name="email" class="form-control" required="">
              </div>
              <div class="form-group col-xl-6">
                <label>Phone Number <span class="text-danger">*</span></label>
                <input type="text" placeholder="Phone Number" name="phone" class="form-control" required="">
              </div>
              <div class="form-group col-xl-6">
                <label>Country Name</label>
                <input type="text" placeholder="Country Name" name="country" class="form-control" required="">
              </div>
              <div class="form-group col-xl-6">
                <label>City Name</label>
                <input type="text" placeholder="Country Name" name="city" class="form-control" required="">
              </div>
              <div class="form-group col-xl-6">
                <label>Street Address 1 <span class="text-danger">*</span></label>
                <input type="text" placeholder="Street Address One" name="address_1" class="form-control" required="">
              </div>
              <div class="form-group col-xl-6">
                <label>Street Address 2</label>
                <input type="text" placeholder="Street Address Two (Optional)" name="address_2" class="form-control">
              </div>
              <input type="hidden" name="data" value=''>

              <button type="submit" class="btn-custom primary btn-block">Place Order</button>
            </div>

            <!-- /Buyer Info -->

          </div>
          <div class="col-xl-5 checkout-billing">
            <!-- Order Details Start -->
            <table class="ct-responsive-table">
              <thead>
                <tr>
                  <th>Product</th>
                  <th>Qunantity</th>
                  <th>Total</th>
                </tr>
              </thead>
              <tbody class="table-body">
                <tr>
                  <td data-title="Product">
                    <div class="cart-product-wrapper">
                      <div class="cart-product-body">
                        <h6> <a href="#">Pepperoni</a> </h6>
                        <p>21 Inch</p>
                      </div>
                    </div>
                  </td>
                  <td data-title="Quantity">x1</td>
                  <td data-title="Total"> <strong>23.99$</strong> </td>
                </tr>

                <tr class="total">
                  <td>
                    <h6 class="mb-0">Grand Total</h6>
                  </td>
                  <td></td>
                  <td> <strong>56.99$</strong> </td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </form>

    </div>
  </section>
  <!-- Checkout End -->

{% endblock %}


{% block javascript %}
<script type="text/javascript">

  document.querySelector('.checkout-form').addEventListener("submit",(event)=>{
    document.querySelector("input[name=data]").value = localStorage.getItem("data")
    EMPTY()
  })

</script>
{% endblock %}

core/templates/menu.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
  <title>Menu</title>
{% endblock %}

{% block content %}

{% for product in products %}
  <div class="modal fade" id="customizeModal{{ product.pk }}" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header modal-bg" style="background-image: url({% static 'img/11.jpg' %})">
          <span class="my-data" data-n="{{ product.name }}" data-p = "{{ product.pk }}" data-i = "{{ product.image }}"></span>
          <button type="button" class="close-btn" data-dismiss="modal" aria-label="Close">
            <span></span>
            <span></span>
          </button>

        </div>
        <div class="modal-body">

          <div class="customize-meta">
            <h4 class="customize-title">{{ product.name }} <span class="custom-primary">{{ product.price }} $</span> </h4>
            <p>
              {{ product.description }}
            </p>
          </div>

          <div class="customize-variations">

            <div class="customize-size-wrapper">
              <h5>Size: </h5>
              {% for i in product.size_set.all %}
              <div class="customize-size sizer {% if forloop.counter == 1 %}active{%endif%}" data-s="{{ i.pk }}" data-price = "{{ i.price }}" data-size = "{{ i.name }}">
                {{ i.name }}
              </div>
              {% endfor %}
            </div>
          </div>

          <div class="customize-controls">
            <div class="qty">
              <span class="qty-subtract"><i class="fas fa-minus"></i></span>
              <input disabled="true" type="text" name="qty" value="1">
              <span class="qty-add"><i class="fas fa-plus"></i></span>
            </div>
            <div class="customize-total" data-price="{{ product.price }}">
              <h5>Total Price: <span class="final-price custom-primary">{{ product.price }} <span>$</span> </span> </h5>
            </div>
          </div>

          <button type="button" class="btn-custom btn-block">Add To Cart</button>

        </div>
      </div>
    </div>
  </div>
{% endfor %}


  <!-- Subheader Start -->
  <div class="subheader dark-overlay dark-overlay-2" style="background-image: url({% static 'img/subheader.jpg' %})">
    <div class="container">
      <div class="subheader-inner">
        <h1>Menu</h1>
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'core:home' %}">Home</a></li>
            <li class="breadcrumb-item"><a href="#">Menu</a></li>
          </ol>
        </nav>
      </div>

    </div>
  </div>
  <!-- Subheader End -->

  <!-- Menu Categories Start -->
  <div class="ct-menu-categories menu-filter">
    <div class="container">
      <div class="menu-category-slider">
          <a href="#" data-filter="*" class="ct-menu-category-item active" data-slick-index="0" aria-hidden="false" tabindex="0" style="width: 113px;">
          <div class="menu-category-thumb">
            <img src="{% static 'img/menu/6.jpg' %}" alt="category">
          </div>
          <div class="menu-category-desc">
            <h6>All</h6>
          </div>
        </a>

        <a href="#" data-filter=".Pizzas" class="ct-menu-category-item" data-slick-index="2" aria-hidden="false" tabindex="0" style="width: 113px;">
          <div class="menu-category-thumb">
            <img src="{% static 'img/menu/2.jpg' %}" alt="category">
          </div>
          <div class="menu-category-desc">
            <h6>Pizzas</h6>
          </div>
        </a>

        <a href="#" data-filter=".Beverages" class="ct-menu-category-item" data-slick-index="6" aria-hidden="false" tabindex="0" style="width: 113px;">
          <div class="menu-category-thumb">
            <img src="{% static 'img/menu/5.jpg' %}" alt="category">
          </div>
          <div class="menu-category-desc">
            <h6>Beverages</h6>
          </div>
        </a>

      </div>
    </div>
  </div>
  <!-- Menu Categories End -->

  <!-- Menu Wrapper Start -->
  <div class="section section-padding">
    <div class="container">

      <div class="menu-container row" style="position: relative; height: 1897.2px;">

        {% for product in products %}


        <!-- Product Start -->
        <div class="col-lg-4 col-md-6 {{ product.catagory }}" style="position: absolute; left: 0px; top: 0px;">
          <div class="product">
            <a class="product-thumb" href="{% url 'core:product' product.pk %}"> <img src="{{ product.sm_image }}" alt="menu item"> </a>
            <div class="product-body">
              <div class="product-desc">
                <h4> <a href="{% url 'core:product' product.pk %}">{{ product.name }}</a> </h4>
                <p>{{ product.description }}</p>
                <p class="product-price">{{ product.price }}$</p>
                <div class="favorite">
                  <i class="far fa-heart"></i>
                </div>
              </div>
              <div class="product-controls">
                <a href="#" data-p="{{ product.pk }}" class="order-item btn-custom btn-sm shadow-none">Add To Cart<i class="fas fa-shopping-cart"></i> </a>
                <a href="#" class="btn-custom secondary btn-sm shadow-none" data-toggle="modal" data-target="#customizeModal{{ product.pk }}"> See Options <i class="fas fa-plus"></i> </a>
              </div>
            </div>
          </div>
        </div>
        <!-- Product End -->
        {% endfor %}
      </div>

    </div>
  </div>
  <!-- Menu Wrapper End -->

{% endblock %}

{% block javascript %}
<script type="text/javascript">
  document.querySelectorAll(".sizer").forEach((item)=>{
    item.addEventListener("click",(event)=>{
      item.parentNode.parentNode.parentNode.querySelector('.active').classList.remove("active")
      item.classList.add("active")
      let newprice = parseFloat(item.getAttribute("data-price"))
      let quantity = parseFloat(item.parentNode.parentNode.parentNode.querySelector("input[name=qty]").value)
      item.parentNode.parentNode.parentNode.querySelector('.final-price').innerHTML = `${(newprice * quantity).toFixed(2)} $`
      item.parentNode.parentNode.parentNode.querySelector('.custom-primary').innerHTML = `${newprice} $`
    })
  })

  document.querySelectorAll(".qty-subtract").forEach((item)=>{
    item.parentNode.parentNode.parentNode.parentNode.addEventListener("click",(event)=>{
      let current = parseFloat(item.parentNode.parentNode.parentNode.parentNode.querySelector('.custom-primary').innerHTML)
      let quantity = parseFloat(item.parentNode.parentNode.parentNode.parentNode.querySelector("input[name=qty]").value)
      if(quantity > 0){
          item.parentNode.parentNode.parentNode.parentNode.querySelector('.final-price').innerHTML = `${(current * quantity).toFixed(2)} $`
      }
    })
  })

  document.querySelectorAll('.modal').forEach((item)=>{
    item.querySelector('.btn-custom').addEventListener('click',(event)=>{
      let data = {}
      data.i = item.querySelector('.my-data').getAttribute('data-i')
      data.p = item.querySelector('.my-data').getAttribute('data-p')
      data.n = item.querySelector('.my-data').getAttribute('data-n')
      data.q = item.querySelector("input[name=qty]").value
      data.s = item.querySelector(".active").getAttribute('data-s')
      data.size = item.querySelector(".active").getAttribute('data-size')
      data.price = parseFloat(item.querySelector('.custom-primary').innerHTML)
      ADD(data)
      item.querySelector(".btn-custom").innerHTML = 'Added'
    })
  })

  document.querySelectorAll('.order-item').forEach((item)=>{
    item.addEventListener('click',(event)=>{
      event.preventDefault()
      let num = item.getAttribute("data-p")
      let neww = document.querySelector(`#customizeModal${num}`)
      let data = {}
      data.i = neww.querySelector('.my-data').getAttribute('data-i')
      data.p = neww.querySelector('.my-data').getAttribute('data-p')
      data.n = neww.querySelector('.my-data').getAttribute('data-n')
      data.q = neww.querySelector("input[name=qty]").value
      data.s = neww.querySelector(".active").getAttribute('data-s')
      data.size = neww.querySelector(".active").getAttribute('data-size')
      data.price = parseFloat(neww.querySelector('.custom-primary').innerHTML)
      ADD(data)
      item.innerHTML = 'Added <i class="fas fa-shopping-cart">'

    })
  })

</script>

{% endblock %}

core/templates/product.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
  <title>Product Page</title>
{% endblock %}

{% block content %}

  <!-- Subheader Start -->
  <div class="subheader dark-overlay dark-overlay-2" style="background-image: url({% static 'img/subheader.jpg' %})">
    <div class="container">
      <div class="subheader-inner">
        <h1>Menu Item</h1>
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'core:home' %}">Home</a></li>
            <li class="breadcrumb-item"><a href="{% url 'core:menu' %}">Menu</a></li>
            <li class="breadcrumb-item active" aria-current="page">Product Page</li>
          </ol>
        </nav>
      </div>

    </div>
  </div>
  <!-- Subheader End -->

  <div class="section product-single">
    <div class="container">

      <div class="row">
        <div class="col-md-5">

          <!-- Main Thumb -->
          <div class="product-thumb">
            <img src="{{ product.image }}" alt="pizza">
          </div>
          <!-- /Main Thumb -->

        </div>
        <div class="col-md-7">
          <div class="product-content">
            <span class="my-data" data-n="{{ product.name }}" data-p = "{{ product.pk }}" data-i = "{{ product.image }}"></span>

            <!-- Product Title -->
            <h2 class="title">{{ product.name }}</h2>
            <!-- /Product Title -->

            <div class="favorite">
              <i class="far fa-heart"></i>
            </div>


            <!-- Price -->
            <div class="price-wrapper">
              <p class="product-price">{{ product.price }}$</p>
            </div>
            <!-- /Price -->

            <!-- Product Short Description -->
            <p>{{ product.description }}</p>
            <!-- /Product Short Description -->

            <!-- Variations -->
            <div class="customize-variations">

              <div class="customize-size-wrapper">
                <h5>Size: </h5>
                {% for i in sizes %}
                  <div class="sizer customize-size {% if forloop.counter == 1 %}active{%endif%}" data-s="{{ i.pk }}" data-price = "{{ i.price }}" data-size = "{{ i.name }}">
                    {{ i.name }}
                  </div>                
                {% endfor %}
              </div>

            </div>
            <!-- /Variations -->

            <!-- Add To Cart Form -->
            <form class="atc-form" method="post">
              <div class="form-group">
                <label>Quantity</label>
                <div class="qty">
                  <span class="qty-subtract"><i class="fas fa-minus"></i></span>
                  <input type="text" name="qty" value="1" disabled="true">
                  <span class="qty-add"><i class="fas fa-plus"></i></span>
                </div>
              </div>
              <button type="submit" name="button" class="btn-custom secondary fff"> Add To Cart <i class="fas fa-shopping-cart"></i> </button>
            </form>
            <!-- /Add To Cart Form -->

            <!-- Product Meta -->
            <ul class="product-meta">
              <li>
                <span>Categories: </span>
                <div class="product-meta-item">
                  <a href="#">Pizza</a>
                </div>
              </li>
              <li>
                <span>Tags: </span>
                <div class="product-meta-item">
                  <a href="#">Pizza</a>,
                  <a href="#">Cheese</a>,
                  <a href="#">Cheesy Crusts</a>
                </div>
              </li>
              <li>
                <span>SKU: </span>
                <div class="product-meta-item">
                  <span>N/A</span>
                </div>
              </li>
            </ul>
            <!-- /Product Meta -->

          </div>
        </div>
      </div>

    </div>
  </div>

  <div class="section pt-0">
    <div class="container">
      <!-- Additional Information Start -->
      <div class="product-additional-info">
        <div class="tab-content" id="bordered-tabContent">
          <div class="tab-pane fade show active" id="tab-product-desc" role="tabpanel" aria-labelledby="tab-product-desc-tab">
            <h4>Description</h4>
            Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute,
            non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a
            bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica
          </div>
        </div>
      </div>
      <!-- Additional Information End -->
    </div>
  </div>

  <!-- Related Start -->
  <div class="section section-padding related-products pt-0">
    <div class="container">
      <h3>You might also like</h3>

      <div class="row menu-v2">
        <!-- Product Start -->
        {% for pizza in pizzas %}
        <div class="col-lg-4 col-md-6">
          <div class="product">
            <div class="favorite">
              <i class="far fa-heart"></i>
            </div>
            <a class="product-thumb" href="{% url 'core:product' pizza.pk %}"> <img src="{{ pizza.image }}" alt="menu item"> </a>
            <div class="product-body">
              <div class="product-desc">
                <h4> <a href="{% url 'core:product' pizza.pk %}">{{ pizza.name }}</a> </h4>
                <p>{{ pizza.description }}</p>
              </div>
              <div class="product-controls">
                <p class="product-price">{{ pizza.price }}$</p>
                <a href="{% url 'core:product' pizza.pk %}" class="order-item btn-custom btn-sm shadow-none">Add To Cart <i class="fas fa-shopping-cart"></i> </a>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
        <!-- Product End -->

      </div>

    </div>
  </div>
  <!-- Related End -->

{% endblock %}


{% block javascript %}
<script type="text/javascript">
  document.querySelectorAll(".sizer").forEach((item)=>{
    item.addEventListener("click",(event)=>{
      item.parentNode.parentNode.querySelector('.active').classList.remove("active")
      item.classList.add("active")
      let newprice = parseFloat(item.getAttribute("data-price"))
      document.querySelector('.product-price').innerHTML = `${newprice} $`
    })
  })

  document.querySelector('.fff').addEventListener('click',(event)=>{
      event.preventDefault()
      let item = document.querySelector('.my-data')
      let num = item.getAttribute("data-p")
      let data = {}
      data.i = item.getAttribute('data-i')
      data.p = item.getAttribute('data-p')
      data.n = item.getAttribute('data-n')
      data.q = document.querySelector("input[name=qty]").value
      data.s = document.querySelector("div.sizer.customize-size.active").getAttribute('data-s')
      data.size = document.querySelector("div.sizer.customize-size.active").getAttribute('data-size')
      data.price = parseFloat(document.querySelector('.product-price').innerHTML)
      ADD(data)
      event.target.innerHTML = 'Added <i class="fas fa-shopping-cart">'

  })

</script>

{% endblock %}

core/templates/thankyou.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
  <title>Thank You</title>
{% endblock %}




{% block content %}

  <div class="subheader dark-overlay dark-overlay-2" style="background-image: url({% static 'img/subheader.jpg' %})">
    <div class="container">
      <div class="subheader-inner">
        <h1>Thank You</h1>
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'core:home' %}">Home</a></li>
            <li class="breadcrumb-item active" aria-current="page">Thank You</li>
          </ol>
        </nav>
      </div>

    </div>
  </div>

  <div class="contact-wrapper">
    <div class="">
      <div class="section pt-5">
        <div class="container">

          <div class="section-title-wrap mt-5 mb-5">
            <h3 class="text-center">Thank You for placing order! You order id is : {{number}} </h3>
          </div>

        </div>
      </div>
    </div>

  </div>

{% endblock %}

core/templates/track_order.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
  <title>Track Your Order</title>
{% endblock %}




{% block content %}

  <div class="subheader dark-overlay dark-overlay-2" style="background-image: url({% static 'img/subheader.jpg' %})">
    <div class="container">
      <div class="subheader-inner">
        <h1>Track Order</h1>
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'core:home' %}">Home</a></li>
            <li class="breadcrumb-item active" aria-current="page">Track Order</li>
          </ol>
        </nav>
      </div>

    </div>
  </div>

  <div class="contact-wrapper">
    <div class="">
      <div class="section pt-5">
        <div class="container">

          <form class="my-form">
            <div class="row">
              <div class="col-lg-3">
              </div>
              <div class="form-group col-lg-5">
                <input required type="text" placeholder="Enter Your ID" class="form-control id" name="fname" value="">
              </div>
              <div class="form-group col-lg-4">
                <button type="submit" class="btn-custom primary" name="button">Track</button>
              </div>
            </div>
          </form>

          <div class="section-title-wrap mt-5 mb-5">
            <h3 class="text-center msg"></h3>
          </div>

        </div>
      </div>
    </div>

  </div>

<script type="text/javascript">
  document.querySelector(".my-form").addEventListener("submit",(event)=>{
      event.preventDefault()
      $.get(`/api/track-order/${document.querySelector(".id").value}/`, function(data, status){
        document.querySelector('.msg').innerHTML = data.message
      });
  })
</script>

{% endblock %}